services:
  api:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
  db:
    image: mysql:9.2.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 55
      start_period: 5s
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
