services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev