services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app/src:ro"
    environment:
      - WATCHPACK_POLLING=TRUE